openapi: 3.0.3
info:
  title: ToolHive Registry Management API - Servers
  version: 1.0.0
  description: API for managing servers within registries

paths:
  /api/v1/registries/{registryId}/servers:
    get:
      summary: List servers in registry
      description: Retrieve all servers available in a specific registry
      parameters:
        - name: registryId
          in: path
          required: true
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
          description: Filter by server category
        - name: tier
          in: query
          schema:
            type: string
            enum: [official, community]
        - name: transport
          in: query
          schema:
            type: string
            enum: [stdio, http, sse]
        - name: search
          in: query
          schema:
            type: string
          description: Search in name, description, and capabilities
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of servers
          content:
            application/json:
              schema:
                type: object
                properties:
                  servers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Server'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
        '404':
          description: Registry not found
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/servers/{serverId}:
    get:
      summary: Get server details
      description: Retrieve detailed information about a specific server
      parameters:
        - name: serverId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Server details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetails'
        '404':
          description: Server not found
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/servers/{serverId}/deploy:
    post:
      summary: Deploy server instance
      description: Create a new deployment of the server to Kubernetes cluster
      parameters:
        - name: serverId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentRequest'
      responses:
        '202':
          description: Deployment initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Server not found
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    Server:
      type: object
      properties:
        id:
          type: string
        registryId:
          type: string
        name:
          type: string
        description:
          type: string
        version:
          type: string
        image:
          type: string
        transport:
          type: string
          enum: [stdio, http, sse]
        tier:
          type: string
          enum: [official, community]
        status:
          type: string
          enum: [available, deprecated, experimental]
        category:
          type: array
          items:
            type: string
        capabilities:
          type: array
          items:
            type: string
        repositoryUrl:
          type: string
          format: uri
        pullCount:
          type: integer
        stars:
          type: integer
        lastUpdated:
          type: string
          format: date-time
      required:
        - id
        - registryId
        - name
        - version
        - image
        - transport
        - tier
        - status

    ServerDetails:
      allOf:
        - $ref: '#/components/schemas/Server'
        - type: object
          properties:
            networkPermissions:
              type: object
              properties:
                allowNetwork:
                  type: boolean
                allowedHosts:
                  type: array
                  items:
                    type: string
            deploymentRequirements:
              type: object
              properties:
                minCpu:
                  type: string
                minMemory:
                  type: string
                storage:
                  type: string
                ports:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                      protocol:
                        type: string
                        enum: [TCP, UDP]
            instances:
              type: array
              items:
                $ref: '#/components/schemas/InstanceSummary'

    InstanceSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        namespace:
          type: string
        status:
          type: string
          enum: [pending, running, failed, terminated]
        deployedAt:
          type: string
          format: date-time
        replicas:
          type: object
          properties:
            desired:
              type: integer
            current:
              type: integer
            ready:
              type: integer

    DeploymentRequest:
      type: object
      properties:
        name:
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          minLength: 1
          maxLength: 63
        namespace:
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          minLength: 1
          maxLength: 63
        replicas:
          type: integer
          minimum: 1
          maximum: 10
          default: 1
        resources:
          type: object
          properties:
            requests:
              type: object
              properties:
                cpu:
                  type: string
                memory:
                  type: string
            limits:
              type: object
              properties:
                cpu:
                  type: string
                memory:
                  type: string
        environment:
          type: object
          additionalProperties:
            type: string
        configuration:
          type: object
          additionalProperties: true
      required:
        - name
        - namespace

    DeploymentResponse:
      type: object
      properties:
        deploymentId:
          type: string
        instanceId:
          type: string
        status:
          type: string
          enum: [initiated]
        estimatedTime:
          type: string
        trackingUrl:
          type: string
          format: uri

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: array
                items:
                  type: string

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string